modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''A Minecraft library that adds tooltips \nto items through translation keys and (a bit) more!

Special text effects are powered by Ember's Text API.
Documentation available at tysontheember.dev.
Jar-in-jar inclusion has been explicitly approved for this mod.
See Ember's Modding License for details.
'''

[[mixins]]
config="libtooltips.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
